package:
  name: "pymodia"
  version: "0.1.0.0"

source:
  path: .

requirements:
  build:
    - numpy
    - drawsvg
    - python {{ python }}

  host:
    - pip
    - python
    - setuptools
    - numpy
    - drawsvg

  run:
    - python
    - numpy
    - drawsvg

test:
  requires:
    - numpy
    - drawsvg
    - setuptools
    - nose
  source_files:
    - tests/*.py
    - tests/results/*.svg
  commands:
    - nosetests tests

about:
  home: https://github.com/ifilot/pymodia
  license: GPL3
  license_family: GPL
  summary: Python package making SVG images of molecular orbital diagrams
  description: See the package README.md for more information.
